name: Exploring Github Actions

on: [push]

jobs:

  Fastfetch-Output:
    runs-on: ubuntu-latest
    steps:
      - run: sudo add-apt-repository 'ppa:zhangsongcui3371/fastfetch'
      - run: sudo apt-get update
      - run: sudo apt-get install -qq fastfetch
      - run: fastfetch

  Compile-Linux-Kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Compilation Process
        run: ./compile.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Compiled binary
          path: vmlinuz
